=== ecalot/cuspop/cuspop/standards/ph1.dtd
<?xml version="1.0"?>

<!ELEMENT princehack ((files|hacks|defines)*)>
<!ELEMENT files ((file)*)>
<!ELEMENT file (#PCDATA)>
<!ELEMENT hacks ((folder|hack)*)>
<!ELEMENT defines ((enum)*)>
<!ELEMENT folder ((folder|hack)*)>
<!ELEMENT hack ((offset|check|read|group)*)>
<!ELEMENT group ((offset|check|read|group)*)>
<!ELEMENT read ((option)*)>
<!ELEMENT enum ((option)*)>
<!ELEMENT offset (#PCDATA)>
<!ELEMENT option (#PCDATA)>
<!ELEMENT check (#PCDATA)>

<!ATTLIST princehack version CDATA #REQUIRED>

<!ATTLIST enum names CDATA #REQUIRED>

<!ATTLIST file path CDATA #REQUIRED>
<!ATTLIST file name CDATA #REQUIRED>
<!ATTLIST file version CDATA #REQUIRED>
<!ATTLIST file md5 CDATA #REQUIRED>
<!ATTLIST file default (true) #IMPLIED>
<!ATTLIST file repack (true) #IMPLIED>
<!ATTLIST file hide (true) #IMPLIED>

<!ATTLIST folder name CDATA #REQUIRED>
<!ATTLIST folder help CDATA #IMPLIED>

<!ATTLIST hack help CDATA #IMPLIED>
<!ATTLIST hack name CDATA #REQUIRED>

<!ATTLIST group name CDATA #REQUIRED>

<!ATTLIST option value CDATA #IMPLIED>
<!ATTLIST option default (true) #IMPLIED>

<!ATTLIST read type CDATA #IMPLIED>
<!ATTLIST read name CDATA #IMPLIED>
<!ATTLIST read minval CDATA #IMPLIED>
<!ATTLIST read maxval CDATA #IMPLIED>
<!ATTLIST read writeoperation CDATA #IMPLIED>
<!ATTLIST read readoperation CDATA #IMPLIED>
<!ATTLIST read help CDATA #IMPLIED>
<!ATTLIST read duplicated CDATA #IMPLIED>
<!ATTLIST read default CDATA #IMPLIED>
<!ATTLIST read size CDATA #IMPLIED>
<!ATTLIST read use (checkbox) #IMPLIED>
<!ATTLIST read enum CDATA #IMPLIED>

<!ATTLIST offset file CDATA #REQUIRED>
<!ATTLIST offset value CDATA #REQUIRED>
<!ATTLIST check codes CDATA #REQUIRED>

=== ecalot/cuspop/cuspop/standards/princehack.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE princehack SYSTEM "http://www.princed.org/standards/xml/ph1.dtd">
<princehack version="1.3">
	<files>
		<file path="prince.exe" name="p0" version="1.0 packed cracked" md5="064b9d41972630f2cf26a4732ff29d13" hide="true"/>
		<file path="prince.exe" name="p3" version="1.3 packed" md5="11179ff0742a2dd352100ad5d8eb267b" hide="true" />
		<file path="prince.exe" name="p4" version="1.4 packed" md5="b5f6b025722a875a32643c800d244af1" hide="true" />
		<file path="prince.exe" name="u0" version="1.0 unpacked cracked" md5="877db132348c5587c060239c0352b1c0" default="true" repack="true" />
		<file path="prince.exe" name="u3" version="1.3 unpacked" md5="c1ce9f0c5e4d48ef01e77fe2a1d8ae34" repack="true"/>
		<file path="prince.exe" name="u4" version="1.4 unpacked" md5="a8bd77b135f0e4595c911eeb9c70700d" repack="true"/>
	</files>
	<defines>
		<enum name='scenes'>
			<option value="0">none</option>
			<option value="38733240">Princess waiting</option>
			<option value="38733188">Princess sleeping</option>
			<option value="38732621">Princess talking to mouse</option>
			<option value="38732727">Princess feeding mouse</option>
			<option value="38733093">Princess waiting 2</option>
		</enum>
		<enum name='environment'>
			<option value="0">Dungeon</option>
			<option value="1">Palace</option>
		</enum>
		<enum name='guards'>
			<option value="0" default="true">Default guard, using guard.dat</option>
			<option value="1">Fat guard, using fat.dat</option>
			<option value="2">Skeleton, using skel.dat</option>
			<option value="3">Jaffar, using vizier.dat</option>
			<option value="4">Shadow, using shadow.dat</option>
			<option value="-1">No guard, don't load resources</option>
		</enum>
		<enum name='keyboard'>
			<option value="-1">None (deactivate)</option>
			<option value="65">Shift+A</option>
			<option value="66">Shift+B</option>
			<option value="67">Shift+C</option>
			<option value="68">Shift+D</option>
			<option value="69">Shift+E</option>
			<option value="70">Shift+F</option>
			<option value="71">Shift+G</option>
			<option value="72">Shift+H</option>
			<option value="73">Shift+I</option>
			<option value="74">Shift+J</option>
			<option value="75">Shift+K</option>
			<option value="76">Shift+L</option>
			<option value="77">Shift+M</option>
			<option value="78">Shift+N</option>
			<option value="79">Shift+O</option>
			<option value="80">Shift+P</option>
			<option value="81">Shift+Q</option>
			<option value="82">Shift+R</option>
			<option value="83">Shift+S</option>
			<option value="84">Shift+T</option>
			<option value="85">Shift+U</option>
			<option value="86">Shift+V</option>
			<option value="87">Shift+W</option>
			<option value="88">Shift+X</option>
			<option value="89">Shift+Y</option>
			<option value="90">Shift+Z</option>
			<option value="1">Control+A</option>
			<option value="2">Control+B</option>
			<option value="3">Control+C</option>
			<option value="4">Control+D</option>
			<option value="5">Control+E</option>
			<option value="6">Control+F</option>
			<option value="7">Control+G</option>
			<option value="8">Backspace/Control+H</option>
			<option value="9">Tab/Control+I</option>
			<option value="10">Control+J</option>
			<option value="11">Control+K</option>
			<option value="12">Control+L</option>
			<option value="13">Enter/Control+M</option>
			<option value="14">Control+N</option>
			<option value="15">Control+O</option>
			<option value="16">Control+P</option>
			<option value="17">Control+Q</option>
			<option value="18">Control+R</option>
			<option value="19">Control+S</option>
			<option value="20">Control+T</option>
			<option value="21">Control+U</option>
			<option value="22">Control+V</option>
			<option value="23">Control+W</option>
			<option value="24">Control+X</option>
			<option value="25">Control+Y</option>
			<option value="26">Control+Z</option>
			<option value="27">Escape/Ctrl+[/Ctrl,Shft+Esc</option>
			<option value="29">Control+]</option>
			<option value="28">Control+\</option>
			<option value="127">Control+?</option>
			<option value="30">Control+^</option>
			<option value="31">Control+_</option>
			<option value="97">A</option>
			<option value="98">B</option>
			<option value="99">C</option>
			<option value="100">D</option>
			<option value="101">E</option>
			<option value="102">F</option>
			<option value="103">G</option>
			<option value="104">H</option>
			<option value="105">I</option>
			<option value="106">J</option>
			<option value="107">K</option>
			<option value="108">L</option>
			<option value="109">M</option>
			<option value="110">N</option>
			<option value="111">O</option>
			<option value="112">P</option>
			<option value="113">Q</option>
			<option value="114">R</option>
			<option value="115">S</option>
			<option value="116">T</option>
			<option value="117">U</option>
			<option value="118">V</option>
			<option value="119">W</option>
			<option value="120">X</option>
			<option value="121">Y</option>
			<option value="122">Z</option>
			<option value="48">0</option>
			<option value="49">1</option>
			<option value="50">2</option>
			<option value="51">3</option>
			<option value="52">4</option>
			<option value="53">5</option>
			<option value="54">6</option>
			<option value="55">7</option>
			<option value="56">8</option>
			<option value="57">9</option>
			<option value="32">Space/Ctrl+Sp/Shft+Sp</option>
			<option value="91">[ Bracket</option>
			<option value="93">] Bracket</option>
			<option value="123">{ Bracket</option>
			<option value="125">} Bracket</option>
			<option value="40">( Bracket</option>
			<option value="41">) Bracket</option>
			<option value="124">| Vertical bar</option>
			<option value="94">^ Caret</option>
			<option value="126">~ Tilde</option>
			<option value="33">! Exclamation mark</option>
			<option value="63">? Question mark</option>
			<option value="34">" Quotation mark</option>
			<option value="39">' Apostrophe</option>
			<option value="35"># Number sign</option>
			<option value="36">$ Dollar sign</option>
			<option value="37">% Percent sign</option>
			<option value="38">&amp; Ampersand</option>
			<option value="42">* Asterisk</option>
			<option value="43">+ Plus sign</option>
			<option value="45">- Minus sign</option>
			<option value="95">_ Underscore</option>
			<option value="47">/ Slash</option>
			<option value="92">\ Backslash</option>
			<option value="46">. Full stop</option>
			<option value="44">, Comma</option>
			<option value="58">: Colon</option>
			<option value="59">; Semicolon</option>
			<option value="96">Grave accent</option>
			<option value="60">&lt; Less than sign</option>
			<option value="61">= Equals sign</option>
			<option value="62">&gt; Greater than sign</option>
			<option value="64">@</option>
		</enum>
	</defines>
	<hacks>
		<folder name="initial settings">
			<hack name="time available and starting hit points">
				<offset file="p0" value="0x04a1f"/>
				<offset file="u0" value="0x060cf"/>
				<offset file="p3" value="0x04e9f"/>
				<offset file="u3" value="0x055df"/>
				<offset file="p4" value="0x0495b"/>
				<offset file="u4" value="0x05a8b"/>
				<check codes="c7 06 .. .."/>
				<read type="unsigned short int" name="starting minutes left" default="60" minval="0" maxval="65535" help="The minutes the kid has to save his princess"/>
				<check codes="c7 06 .. .."/>
				<read type="unsigned short int" name="starting seconds left" default="719" minval="0" maxval="719" readoperation="tofloat;multiply(100);divide(12);round;divide(100);" writeoperation="multiply(12);floor;tointeger;" help="Remaining seconds to be added to the remaining minutes. This number must be a multiple of 1/12, if it is not, it will be rounded."/>
				<check codes="c7 06 .. .."/>
				<read type="unsigned short int" name="starting hit points" default="3" minval="0" maxval="65535"/>
			</hack>
			<hack name="starting level">
				<offset file="p0" value="0x00703"/>
				<offset file="u0" value="0x01db3"/>
				<offset file="p3" value="0x007d7"/>
				<offset file="u3" value="0x00f17"/>
				<offset file="p4" value="0x0079b"/>
				<offset file="u4" value="0x018cb"/>
				<check codes="c7 06 .. .."/>
				<read type="unsigned short int" name="starting level" default="1" minval="0" maxval="16" help="It will start here, even if you come back from the titles."/>
			</hack>
		</folder>
		<hack name="maximal number of hit points">
			<offset file="p0" value="0x013ec"/>
			<offset file="u0" value="0x02a9c"/>
			<offset file="p3" value="0x015a7"/>
			<offset file="u3" value="0x01ce7"/>
			<offset file="p4" value="0x0149e"/>
			<offset file="u4" value="0x025ce"/>
			<check codes="a1 .. .. 40 3d"/>
			<read type="unsigned short int" name="hit points" default="10" minval="0" maxval="65535" help="Warning: setting a value larger than 10 will cause the hit points display in the lower left corner of the screen to be overlapped by the remaining time messages, so it is discouraged. However, from the point of view of the game, its value is handled correctly."/>
			<check codes="7e 03 b8"/>
			<read duplicated="hit points"/>
			<check codes="a3"/>
		</hack>
		<hack name="minimal and maximal level where you can save">
			<offset file="p0" value="0x007c4"/>
			<offset file="u0" value="0x01e74"/>
			<offset file="p3" value="0x008b0"/>
			<offset file="u3" value="0x00ff0"/>
			<offset file="p4" value="0x00874"/>
			<offset file="u4" value="0x019a4"/>
			<check codes="83 3e .. .."/>
			<read type="unsigned char" name="minimal level" default="2" minval="1" maxval="65535" readoperation="add(1);" writeoperation="subtract(1);"/>
			<check codes="7e .. 83 3e .. .."/>
			<read type="unsigned char" name="maximal level" default="14" minval="0" maxval="65534" readoperation="subtract(1);" writeoperation="add(1);"/>
			<check codes="7d .."/>
		</hack>
		<hack name="flipdown">
			<offset file="p0" value="0x4c9b"/>
			<offset file="u0" value="0x634b"/>
